### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by harsharchduke** [ayushg03/Sahpathi#1]
https://github.com/ayushg03/Sahpathi/blob/28eb9e034c7522ee7279cbf2d5ab0eb604dcb3c7/Server/routes/events.js#L12-L15

We can use js object destructing to make code more readible. Follow the link mentioned below for references-: https://www.javascripttutorial.net/es6/javascript-object-destructuring/

**Comment by ayushg03** [comment]
Updated the code.
